# Generated by Django 4.1 on 2022-11-18 11:46

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(db_index=True, default='First Name: ', max_length=15, null='False', verbose_name='First Name')),
                ('name2', models.CharField(db_index=True, default='Last Name: ', max_length=15, null='False', verbose_name='Last Name')),
                ('image', cloudinary.models.CloudinaryField(blank=True, db_index=True, max_length=255, verbose_name='image')),
                ('code', models.IntegerField(db_index=True, default=91, verbose_name='CountryCode: ')),
                ('phone', models.IntegerField(db_index=True, default=0, verbose_name='Phone No: ')),
                ('email', models.CharField(db_index=True, default='sample@gmail.com', max_length=50, verbose_name='Email:')),
                ('address1', models.CharField(db_index=True, default='House number and street', max_length=30, verbose_name='Address Line 1')),
                ('address2', models.CharField(db_index=True, default='City and state', max_length=30, verbose_name='city,state')),
                ('address3', models.IntegerField(db_index=True, default='00000', verbose_name='pin-code1')),
                ('address4', models.CharField(db_index=True, default='Country', max_length=20, verbose_name='Country')),
                ('work1', models.CharField(db_index=True, default='Employee Designation', max_length=30, verbose_name='Designation')),
                ('desc', models.CharField(db_index=True, default='Discription goes here...', max_length=60, verbose_name='Job Description')),
                ('experience', models.IntegerField(db_index=True, default=0, verbose_name='Work Experience')),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
