# Generated by Django 4.1 on 2022-11-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='address1',
            field=models.CharField(db_index=True, default='House and street', max_length=30, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='address3',
            field=models.IntegerField(db_index=True, default=0, verbose_name='pin-code1'),
        ),
    ]
