# Generated by Django 4.1 on 2022-11-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_address1_alter_portfolio_address3'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='company',
            field=models.CharField(db_index=True, default='Company name', max_length=15, verbose_name='Company'),
        ),
    ]
