# Generated by Django 4.1 on 2022-11-19 13:28

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(db_index=True, default='First Name: ', max_length=15, null='False', verbose_name='First Name')),
                ('name2', models.CharField(db_index=True, default='Last Name: ', max_length=15, null='False', verbose_name='Last Name')),
                ('image', cloudinary.models.CloudinaryField(blank=True, db_index=True, max_length=255, verbose_name='image')),
                ('code', models.IntegerField(db_index=True, default=91, verbose_name='CountryCode: ')),
                ('phone', models.IntegerField(db_index=True, default=0, verbose_name='Phone No: ')),
                ('email', models.CharField(db_index=True, default='sample@gmail.com', max_length=50, verbose_name='Email:')),
                ('address1', models.CharField(db_index=True, default='House and street', max_length=30, verbose_name='Address Line 1')),
                ('address2', models.CharField(db_index=True, default='City and state', max_length=30, verbose_name='city,state')),
                ('address3', models.IntegerField(db_index=True, default=0, verbose_name='pin-code1')),
                ('address4', models.CharField(db_index=True, default='Country', max_length=20, verbose_name='Country')),
                ('company', models.CharField(db_index=True, default='Company name', max_length=15, verbose_name='Company')),
                ('designation', models.CharField(db_index=True, default='Employee Designation', max_length=30, verbose_name='Designation')),
                ('date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Start Date')),
                ('dateend', models.CharField(blank=True, db_index=True, default='Present', max_length=25, verbose_name='End Date')),
                ('ocity', models.CharField(db_index=True, default='Remote', max_length=20, verbose_name='Office City')),
                ('ostate', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Office State')),
                ('desca', models.CharField(db_index=True, default='Discription point one goes here...', max_length=60, verbose_name='Job Description 1st point')),
                ('descb', models.CharField(db_index=True, default='Discription point two goes here...', max_length=60, verbose_name='Job Description 2nd point')),
                ('descc', models.CharField(db_index=True, default='Discription point three goes here...', max_length=60, verbose_name='Job Description 3rd point')),
                ('descd', models.CharField(blank=True, db_index=True, default='Discription point four goes here...', max_length=60, null=True, verbose_name='Job Description 4th point')),
                ('company2', models.CharField(db_index=True, default='Company name', max_length=15, verbose_name='Company')),
                ('designation2', models.CharField(db_index=True, default='Employee Designation', max_length=30, verbose_name='Designation')),
                ('date2', models.DateField(blank=True, db_index=True, null=True, verbose_name='Start Date')),
                ('dateend2', models.CharField(blank=True, db_index=True, default='Present', max_length=25, verbose_name='End Date')),
                ('ocity2', models.CharField(db_index=True, default='Remote', max_length=20, verbose_name='Office City')),
                ('ostate2', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Office State')),
                ('desca2', models.CharField(db_index=True, default='Discription point one goes here...', max_length=60, verbose_name='Job Description 1st point')),
                ('descb2', models.CharField(db_index=True, default='Discription point two goes here...', max_length=60, verbose_name='Job Description 2nd point')),
                ('descc2', models.CharField(db_index=True, default='Discription point three goes here...', max_length=60, verbose_name='Job Description 3rd point')),
                ('descd2', models.CharField(blank=True, db_index=True, default='Discription point four goes here...', max_length=60, null=True, verbose_name='Job Description 4th point')),
                ('company3', models.CharField(db_index=True, default='Company name', max_length=15, verbose_name='Company')),
                ('designation3', models.CharField(db_index=True, default='Employee Designation', max_length=30, verbose_name='Designation')),
                ('date3', models.DateField(blank=True, db_index=True, null=True, verbose_name='Start Date')),
                ('dateend3', models.CharField(blank=True, db_index=True, default='Present', max_length=25, verbose_name='End Date')),
                ('ocity3', models.CharField(db_index=True, default='Remote', max_length=20, verbose_name='Office City')),
                ('ostate3', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Office State')),
                ('desca3', models.CharField(db_index=True, default='Discription point one goes here...', max_length=60, verbose_name='Job Description 1st point')),
                ('descb3', models.CharField(db_index=True, default='Discription point two goes here...', max_length=60, verbose_name='Job Description 2nd point')),
                ('descc3', models.CharField(db_index=True, default='Discription point three goes here...', max_length=60, verbose_name='Job Description 3rd point')),
                ('descd3', models.CharField(blank=True, db_index=True, default='Discription point four goes here...', max_length=60, null=True, verbose_name='Job Description 4th point')),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
